/**
 * generate-pages.mjs
 *
 * Scans src/components/, src/patterns/, src/templates/ for components
 * with a *.figma-notes.md file. Generates:
 *   - One markdown doc page per component in docs-site/{tier}s/{name}.md
 *   - sidebar-data.json for dynamic VitePress sidebar navigation
 *
 * Components are grouped by Figma source file (Design System vs AI Chat).
 *
 * Run: node docs-site/.vitepress/scripts/generate-pages.mjs
 */

import { readdirSync, readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs'
import { join, resolve } from 'path'

const ROOT = resolve(import.meta.dirname, '..', '..', '..')
const DOCS_SITE = resolve(ROOT, 'docs-site')

const TIERS = [
  { dir: 'src/components', tier: 'component', outDir: 'components' },
  { dir: 'src/patterns', tier: 'pattern', outDir: 'patterns' },
  { dir: 'src/templates', tier: 'template', outDir: 'templates' },
]

// ── Figma file key → product mapping ───────────────────
const FILE_KEY_MAP = {
  'Lus07xi8pPXLN87sQIyrEt': { product: 'designSystem', label: 'Design System', badgeType: 'info' },
  'Ikv8jxb5dcRH8ff4q4dR11': { product: 'aiChat', label: 'AI Chat', badgeType: 'tip' },
}

function getProductFromUrl(figmaUrl) {
  if (!figmaUrl) return null
  for (const [key, value] of Object.entries(FILE_KEY_MAP)) {
    if (figmaUrl.includes(key)) return value
  }
  return null
}

// ── Parse component-registry.md for metadata ────────────
function parseRegistry() {
  const registryPath = join(ROOT, 'docs/component-registry.md')
  if (!existsSync(registryPath)) return {}

  const content = readFileSync(registryPath, 'utf-8')
  const lines = content.split('\n')
  const registry = {}

  for (const line of lines) {
    if (!line.startsWith('|') || line.startsWith('| Component') || line.startsWith('|---')) continue
    const cols = line.split('|').map(c => c.trim()).filter(Boolean)
    if (cols.length >= 4) {
      const name = cols[0]
      const tier = cols[1]
      const status = cols[2]

      // Extract URL from markdown link
      const urlMatch = cols[3].match(/\[.*?\]\((.*?)\)/)
      const figmaUrl = urlMatch ? urlMatch[1] : ''

      const notes = cols[4] || ''

      registry[name] = { tier, status, figmaUrl, notes }
    }
  }
  return registry
}

// ── Parse figma-notes.md sections ───────────────────────
function parseFigmaNotes(filePath) {
  const content = readFileSync(filePath, 'utf-8')
  const sections = {}
  let currentSection = '_header'
  let currentContent = []

  for (const line of content.split('\n')) {
    if (line.startsWith('## ')) {
      if (currentContent.length) {
        sections[currentSection] = currentContent.join('\n').trim()
      }
      currentSection = line.replace('## ', '').trim()
      currentContent = []
    } else {
      currentContent.push(line)
    }
  }
  if (currentContent.length) {
    sections[currentSection] = currentContent.join('\n').trim()
  }

  return sections
}

// ── Convert PascalCase to kebab-case ────────────────────
function toKebab(name) {
  return name
    .replace(/([a-z])([A-Z])/g, '$1-$2')
    .replace(/([A-Z])([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

// ── Generate a markdown page for one component ──────────
function generatePage(name, tierInfo, sections, registryEntry) {
  const kebab = toKebab(name)
  const demoPath = `/demos/${tierInfo.dir}/${name}/${name}.html`
  const figmaUrl = registryEntry?.figmaUrl || ''
  const description = registryEntry?.notes || ''
  const product = getProductFromUrl(figmaUrl)

  // Extract short description from notes (first sentence before " — ")
  const shortDesc = description.includes('—')
    ? description.split('—').slice(1).join('—').trim().split('.')[0]
    : ''

  let md = `<!-- AUTO-GENERATED by generate-pages.mjs — do not edit -->\n`
  md += `---\ntitle: ${name}\n---\n\n`
  md += `# ${name}`

  // Add source badge
  if (product) {
    md += ` <Badge type="${product.badgeType}" text="${product.label}" />`
  }
  md += `\n\n`

  if (shortDesc) {
    md += `> ${shortDesc}\n\n`
  }

  md += `<ComponentDemo src="${demoPath}" />\n\n`

  // Structured sections that go into the "Reference" group at the bottom
  const structuredSections = new Set([
    'Variant × Size × State Matrix', 'Variant Matrix',
    'CSS Class Mapping', 'Token Mapping', 'Token Gaps',
    'Token Gaps — Action Required in Figma',
    'Icon Slots (text-button variants)', 'Notes',
  ])

  // Sections to skip entirely (metadata, not display content)
  const skipSections = new Set([
    '_header', 'Dependencies', 'Interaction', 'Figma Node',
  ])

  // ── Pass-through sections first (Overview, behaviour docs, etc.) ──
  for (const [sectionName, content] of Object.entries(sections)) {
    if (!structuredSections.has(sectionName) && !skipSections.has(sectionName) && content.trim()) {
      md += `## ${sectionName}\n\n${content}\n\n`
    }
  }

  // ── Structured reference sections ──

  // Variant matrix
  if (sections['Variant × Size × State Matrix'] || sections['Variant Matrix']) {
    const matrixContent = sections['Variant × Size × State Matrix'] || sections['Variant Matrix']
    md += `## Variants\n\n${matrixContent}\n\n`
  }

  // CSS Class Mapping
  if (sections['CSS Class Mapping']) {
    md += `## CSS Classes\n\n${sections['CSS Class Mapping']}\n\n`
  }

  // Token Mapping
  if (sections['Token Mapping']) {
    md += `## Token Mapping\n\n${sections['Token Mapping']}\n\n`
  }

  // Token Gaps
  if (sections['Token Gaps'] || sections['Token Gaps — Action Required in Figma']) {
    const gapsContent = sections['Token Gaps'] || sections['Token Gaps — Action Required in Figma']
    md += `## Token Gaps\n\n${gapsContent}\n\n`
  }

  // Icon Slots (if present)
  if (sections['Icon Slots (text-button variants)']) {
    md += `## Icon Slots\n\n${sections['Icon Slots (text-button variants)']}\n\n`
  }

  // Notes
  if (sections['Notes']) {
    md += `## Notes\n\n${sections['Notes']}\n\n`
  }

  // Figma link
  if (figmaUrl) {
    md += `## Figma\n\n[Open in Figma](${figmaUrl})\n`
  }

  return md
}

// ── Main ────────────────────────────────────────────────
const registry = parseRegistry()

// Grouped sidebar: { designSystem: { components: [] }, aiChat: { components: [], patterns: [], templates: [] } }
const sidebarData = {
  designSystem: { components: [] },
  aiChat: { components: [], patterns: [], templates: [] },
}

let totalPages = 0

for (const tierInfo of TIERS) {
  const srcDir = join(ROOT, tierInfo.dir)
  if (!existsSync(srcDir)) continue

  const outDir = join(DOCS_SITE, tierInfo.outDir)
  if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

  const dirs = readdirSync(srcDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name)
    .sort()

  for (const name of dirs) {
    const compDir = join(srcDir, name)

    // Find figma-notes.md
    const notesFile = join(compDir, `${name}.figma-notes.md`)
    const hasNotes = existsSync(notesFile)

    // Find demo HTML
    const htmlFile = join(compDir, `${name}.html`)
    const hasDemo = existsSync(htmlFile)

    if (!hasNotes && !hasDemo) continue

    const sections = hasNotes ? parseFigmaNotes(notesFile) : {}
    const registryEntry = registry[name]

    const kebab = toKebab(name)
    const md = generatePage(name, tierInfo, sections, registryEntry)
    const outPath = join(outDir, `${kebab}.md`)
    writeFileSync(outPath, md, 'utf-8')
    totalPages++

    // Determine product group from Figma URL
    const product = getProductFromUrl(registryEntry?.figmaUrl)
    const sidebarItem = {
      text: name.replace(/([a-z])([A-Z])/g, '$1 $2'),
      link: `/${tierInfo.outDir}/${kebab}`,
    }

    if (product?.product === 'designSystem') {
      // Design System only has components (no patterns/templates)
      sidebarData.designSystem.components.push(sidebarItem)
    } else {
      // AI Chat (or unknown) — group by tier
      const tierKey = tierInfo.outDir  // 'components', 'patterns', 'templates'
      sidebarData.aiChat[tierKey].push(sidebarItem)
    }
  }
}

// Write sidebar data
const sidebarPath = join(DOCS_SITE, '.vitepress', 'sidebar-data.json')
writeFileSync(sidebarPath, JSON.stringify(sidebarData, null, 2), 'utf-8')

const dsCount = sidebarData.designSystem.components.length
const chatCount = sidebarData.aiChat.components.length + sidebarData.aiChat.patterns.length + sidebarData.aiChat.templates.length
console.log(`Generated ${totalPages} pages:`)
console.log(`  Design System: ${dsCount} components`)
console.log(`  AI Chat:       ${sidebarData.aiChat.components.length} components, ${sidebarData.aiChat.patterns.length} patterns, ${sidebarData.aiChat.templates.length} templates`)
console.log(`Sidebar data: ${sidebarPath}`)
