"""Sort Order source — the 73 live articles in section Insights (StandardSectionCode 17950),
read from the Hub (articles_list, sorted by title) on 2026-09-29. Title order is the section's
default; no explicit sort order is set. Thumbnails are NOT real: picsum placeholders seeded by
the article code, except Article 626312's own image."""

INSIGHTS = [
    (617996, '10 Top Tips for Better Customer Engagement'),
    (626114, 'Affino AI Agents'),
    (626112, 'Affino AI Analyst'),
    (626116, 'Affino AI Chat'),
    (626115, 'Affino AI Copilot'),
    (626157, 'Affino AI Site Plugins'),
    (626196, 'Affino AI: What 2025 Taught Us — and What We’re Building for 2026'),
    (625100, 'Affino Data Breach Policy'),
    (626282, 'Affino for Charities: Agentic Supporter Journeys, Audience CRM, and Connected Campaigns'),
    (625099, 'Affino GDPR Client / Supplier Questionnaire'),
    (626071, 'Affino Gives you More AI Tokens'),
    (625348, 'Affino Intelligence Briefing - August 2020 Site traffic and Email campaigns Diverge'),
    (625321, 'Affino Intelligence Briefing - June 2020 The End of the Coronavirus Traffic Surge'),
    (625474, 'Affino Intelligence Briefing - June 2021 Tougher to Engage Audiences'),
    (625301, 'Affino Intelligence Briefing - May 2020 Site Engagement Trends'),
    (625369, 'Affino Intelligence Briefing - October 2020 Strong Growth on All Key Metrics'),
    (625360, 'Affino Intelligence Briefing - September 2020 Site traffic down to Pre Covid Levels'),
    (626113, 'Affino Mass Content AI'),
    (625388, 'Affino Ramps Up Services and Support throughout 2020 for a Deeper and More Connected Client Experience'),
    (626111, 'Affino Support AI'),
    (620678, "Affino's GDPR Commitments and Timeline (Updated)"),
    (625588, "Affino's smart audience engagement natively extends GDPR-compliant customer record retention"),
    (625509, "Affino's Smart Built-in Comprehensive Zero and First Party Data Capture Capabilities"),
    (626310, 'AI Advisory Service for Charities'),
    (625390, 'Automation to Elevate your Subscription Model - PPA IPN Think Tank'),
    (620653, 'Best Practice handling of customer data in preparation for GDPR'),
    (625291, 'Developing a Subscription and Membership Offering'),
    (626125, 'Enhanced Affino Commerce & Subscription Capabilities'),
    (626309, 'Five AI workflows every charity can start with'),
    (616651, 'Forget Everything You Know About CRM - Introducing the Affino Core-Connected CRM'),
    (615222, 'Full-Spectrum Customer Engagement Platform Gets You Closer Quicker'),
    (625030, 'GDPR Implementation Checklist'),
    (625696, 'Generative AI, Temperature and Hallucinations'),
    (625375, 'Google Analytics Declining in Effectiveness because of GDPR and Apple'),
    (620677, 'Handy GDPR Definitions Guide'),
    (625503, "Highlights from Affino's Subscription and Membership Think Tank"),
    (625566, "How Affino's Full Service Fidelity Delivers More Zero and First Party Data Capture and Superior Analytics"),
    (625764, 'How best to Tune your Expert AI Services'),
    (626308, 'How charities are getting real value from AI'),
    (626312, 'How charities can use Affino AI plugins'),
    (616053, 'How Drewry Combine Enterprise, Experts and Evidence for maximum Credentials Impact'),
    (625703, 'How to Deliver AI Prototypes and Proofs of Concept - The Key Questions Answered'),
    (625245, 'How to Design and Build a Topic Hub - Video Guide'),
    (625293, 'How to Improve and Leverage your Subscription and Membership Experiences'),
    (616590, 'How to leverage engagement through Content Metering'),
    (617626, 'In the War for Attention - You have to Make Every Click Count'),
    (626124, "Introducing Affino's Fourth Generation AI Services"),
    (626123, "Introducing Affino's new Control Centre"),
    (626096, "Introducing Affino's Six AI Engines"),
    (626092, 'Key Affino Insights 2024 Generated via AIs'),
    (625287, 'Key Affino Subscription and Membership Tools'),
    (625490, 'Learnings from our first Affino Think Tank'),
    (615026, 'Leverage social connectivity through social media embeds'),
    (625350, "Making the most of Affino's new Loyalty Scheme SaaS Solution"),
    (625292, 'Migrating from Free to Paid Subscriptions and Memberships'),
    (625383, 'New Media and Events Revenue Opportunities'),
    (625544, 'PPA Affino Roundtable - Sunsetting Of Cookies, First Party and Contextual Data Solutions and the Impact On Digital Marketing'),
    (615508, 'Procurement Leaders at the forefront of event engagement'),
    (615430, 'Professional Services Brands Succeeding on the Affino Platform'),
    (617891, 'Related Items Strategy'),
    (617153, "Sales and Marketing Automation and Abraham Maslow's Hierarchy of Needs"),
    (626263, 'Test Insights — Round-Trip Verification (2026-05-10)'),
    (625762, 'The Affino AI Journey'),
    (625246, 'The Complimentary nature of Zoom and Affino for delivering Webinars'),
    (618452, 'The Essence of Customer Engagement'),
    (626097, 'The Evolved Web - Top Tips on how to use AI to transform the web experience'),
    (625760, 'The Great Leap Forward from Articles and Documents to Expert AI services'),
    (626303, "The Operator's AI Playbook: Turning Proprietary Intelligence into Live Customer Value"),
    (614953, 'The Trifecta of Professional Services Credentials - Enterprise, Experts and Evidence'),
    (626141, 'Tips for setting up your first Agentic AI Website'),
    (617261, 'UK Media Ad Blocking and Privacy Briefing June 2017'),
    (625761, 'What are the elements of Affino’s Enterprise-Grade Expert AI Service'),
    (625763, 'What can and can’t you do with Affino’s Enterprise Expert AI Service'),
]
