/* ApiProfileHelp — behaviour for both API help screens (TASK-470997, TASK-470998).
 *
 *   1. Full width: every card takes RecordSection Width=Full, following `cc:width` (as UpdateScreen).
 *   2. On this page: the link for the section in view is marked aria-current (scroll-spy), and a
 *      link click scrolls inside the CC page column (the shell's scroller, not the window). On a
 *      narrow page column the rail is replaced by one sticky Select that does the same.
 *
 * The content itself is static, generated by _generate.py from the classic CFML.
 */
(function () {
  'use strict';

  var page = document.querySelector('.cc-api-help');
  if (!page) return;

  /* ── 1. Full width ────────────────────────────────────────────── */
  function mirror(mode) {
    var full = mode === 'full';
    page.querySelectorAll('.record-section').forEach(function (s) { s.classList.toggle('record-section--full', full); });
  }
  document.addEventListener('cc:width', function (e) { mirror(e.detail.mode); });
  var shell = document.querySelector('.cc-control');
  mirror(shell ? shell.getAttribute('data-cc-width') : 'standard');

  /* ── 2. On this page ──────────────────────────────────────────── */
  var links = [].slice.call(page.querySelectorAll('.cc-api-help__toc-link'));
  var byId = {};
  links.forEach(function (a) { byId[a.getAttribute('href').slice(1)] = a; });

  /* The narrow-screen Select mirrors the rail: its value is the section in view. */
  var jump = page.querySelector('.cc-api-help__jump');
  var jumpValue = jump && jump.querySelector('[data-jump-value]');
  var jumpCount = jump && jump.querySelector('[data-jump-count]');

  function mark(id) {
    links.forEach(function (a) { a.setAttribute('aria-current', byId[id] === a ? 'true' : 'false'); });
    if (!jump) return;
    jump.querySelectorAll('[data-jump]').forEach(function (opt) {
      var on = opt.getAttribute('data-jump') === id;
      opt.classList.toggle('sel__menu-item--selected', on);
      /* The tick moves with the selection, as Select.js moves it on a click. */
      var tick = opt.querySelector('[data-lucide], svg');
      if (on) {
        opt.setAttribute('aria-selected', 'true');
        jumpValue.textContent = opt.querySelector('.cc-api-help__jump-label').textContent;
        /* The closed Select shows the section's endpoint count too, as the rail does. */
        var chip = opt.querySelector('.cc-api-help__count');
        jumpCount.hidden = !chip;
        if (chip) { jumpCount.textContent = chip.textContent; jumpCount.setAttribute('aria-label', chip.getAttribute('aria-label')); }
        if (!tick) { var i = document.createElement('i'); i.setAttribute('data-lucide', 'check'); opt.appendChild(i); }
      } else {
        opt.removeAttribute('aria-selected');
        if (tick) tick.remove();
      }
    });
    if (window.lucide) window.lucide.createIcons();
  }

  function go(id) {
    var target = document.getElementById(id);
    if (!target) return;
    target.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'auto' : 'smooth', block: 'start' });
    history.replaceState(null, '', '#' + id);
    mark(id);
  }

  /* Select.js opens, closes and ticks the option; picking one also jumps. */
  if (jump) {
    jump.addEventListener('click', function (e) {
      var opt = e.target.closest('[data-jump]');
      if (opt) go(opt.getAttribute('data-jump'));
    });
  }

  links.forEach(function (a) {
    a.addEventListener('click', function (e) {
      e.preventDefault();
      go(a.getAttribute('href').slice(1));
    });
  });

  if ('IntersectionObserver' in window) {
    var visible = {};
    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (en) { visible[en.target.id] = en.isIntersecting ? en.intersectionRatio : 0; });
      /* The topmost section with any of itself in the upper part of the view. */
      var sections = page.querySelectorAll('.cc-api-help__section');
      for (var i = 0; i < sections.length; i++) {
        if (visible[sections[i].id] > 0) { mark(sections[i].id); return; }
      }
    }, { rootMargin: '0px 0px -60% 0px', threshold: [0, 0.01] });
    page.querySelectorAll('.cc-api-help__section').forEach(function (s) { io.observe(s); });
  }
  mark((location.hash || '#overview').slice(1));
})();
