/* DatePicker — functional vanilla-JS calendar.
 * Figma node 3039:8761. Renders day / month / year views with single-date and
 * range selection, disabled-past support, and a Today shortcut.
 *
 * Markup contract (see DatePicker.html):
 *   <div class="datepicker" data-datepicker
 *        data-mode="single|range" data-months="1|2"
 *        data-disable-past data-inline data-initial="YYYY-MM-DD">
 *     <!-- popover mode: a trigger field with a [data-datepicker-input] -->
 *   </div>
 * The calendar DOM is generated by this script and appended to the root.
 *
 * Auto-inits every [data-datepicker] on DOMContentLoaded. Icons are (re)created
 * via lucide.createIcons() after each render.
 */
(function () {
  'use strict';

  var MONTHS_SHORT = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  var WEEKDAYS = ['Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa', 'Su']; // Monday-first

  function startOfDay(d) { return new Date(d.getFullYear(), d.getMonth(), d.getDate()); }
  function sameDay(a, b) { return !!a && !!b && a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }
  function addMonths(d, n) { return new Date(d.getFullYear(), d.getMonth() + n, 1); }
  function fmtDate(d) { return d.getDate() + ' ' + MONTHS_SHORT[d.getMonth()] + ' ' + d.getFullYear(); }
  function fmtMonthYear(d) { return ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'][d.getMonth()] + ' ' + d.getFullYear(); }
  function parseISO(s) { var m = /^(\d{4})-(\d{2})-(\d{2})$/.exec(s || ''); return m ? new Date(+m[1], +m[2] - 1, +m[3]) : null; }
  function refreshIcons() { if (window.lucide && typeof window.lucide.createIcons === 'function') window.lucide.createIcons(); }

  function DatePicker(root) {
    this.root = root;
    this.mode = root.dataset.mode === 'range' ? 'range' : 'single';
    this.monthsToShow = (this.mode === 'range' && root.dataset.months === '2') ? 2 : 1;
    this.inline = root.hasAttribute('data-inline');
    this.disablePast = root.hasAttribute('data-disable-past');
    this.today = startOfDay(new Date());
    this.minDate = this.disablePast ? this.today : null;
    this.view = (root.dataset.view === 'months' || root.dataset.view === 'years') ? root.dataset.view : 'days';
    this.input = root.querySelector('[data-datepicker-input]');

    this.selected = null;
    this.rangeStart = null;
    this.rangeEnd = null;

    var init = parseISO(root.dataset.initial);
    var base = init || this.today;
    this.cursor = new Date(base.getFullYear(), base.getMonth(), 1);
    if (init && this.mode === 'single') this.selected = init;

    this.cal = document.createElement('div');
    this.cal.className = 'datepicker__calendar'
      + (this.monthsToShow === 2 ? ' datepicker__calendar--dual' : '')
      + (this.inline ? '' : ' datepicker__calendar--popover');
    root.appendChild(this.cal);

    if (!this.inline) this._wirePopover();
    this.render();
  }

  DatePicker.prototype._wirePopover = function () {
    var self = this;
    var open = function () { self.root.classList.add('datepicker--open'); };
    var close = function () { self.root.classList.remove('datepicker--open'); };
    var toggle = function (e) { e.preventDefault(); self.root.classList.toggle('datepicker--open'); };

    if (this.input) {
      this.input.addEventListener('focus', open);
      this.input.addEventListener('click', toggle);
    }
    var icon = this.root.querySelector('[data-datepicker-toggle]');
    if (icon) icon.addEventListener('click', toggle);

    document.addEventListener('click', function (e) {
      if (!self.root.contains(e.target)) close();
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape') close();
    });
    this._close = close;
  };

  DatePicker.prototype.isDisabled = function (d) {
    return this.minDate && startOfDay(d) < this.minDate;
  };

  DatePicker.prototype.render = function () {
    this.cal.innerHTML = '';
    this.months = document.createElement('div');
    this.months.className = 'datepicker__months';
    this.cal.appendChild(this.months);
    if (this.view === 'months') this._renderMonths();
    else if (this.view === 'years') this._renderYears();
    else this._renderDays();
    this._renderFooter();
    refreshIcons();
  };

  DatePicker.prototype._navButton = function (dir) {
    var self = this;
    var btn = document.createElement('button');
    btn.type = 'button';
    btn.className = 'datepicker__nav-btn';
    btn.setAttribute('aria-label', dir < 0 ? 'Previous' : 'Next');
    btn.innerHTML = '<i data-lucide="' + (dir < 0 ? 'chevron-left' : 'chevron-right') + '" aria-hidden="true"></i>';
    btn.addEventListener('click', function () {
      if (self.view === 'years') self.cursor = new Date(self.cursor.getFullYear() + dir * 12, self.cursor.getMonth(), 1);
      else if (self.view === 'months') self.cursor = new Date(self.cursor.getFullYear() + dir, self.cursor.getMonth(), 1);
      else self.cursor = addMonths(self.cursor, dir);
      self.render();
    });
    return btn;
  };

  DatePicker.prototype._header = function (labelText, titleView) {
    var self = this;
    var header = document.createElement('div');
    header.className = 'datepicker__header';

    var title = document.createElement('button');
    title.type = 'button';
    title.className = 'datepicker__title';
    title.textContent = labelText;
    if (titleView) {
      title.addEventListener('click', function () { self.view = titleView; self.render(); });
    } else {
      title.disabled = true;
    }

    var nav = document.createElement('div');
    nav.className = 'datepicker__nav';
    nav.appendChild(this._navButton(-1));
    nav.appendChild(this._navButton(1));

    header.appendChild(title);
    header.appendChild(nav);
    return header;
  };

  // ── Days view ─────────────────────────────────────────
  DatePicker.prototype._renderDays = function () {
    for (var i = 0; i < this.monthsToShow; i++) {
      this.months.appendChild(this._monthPanel(addMonths(this.cursor, i), i === 0, i === this.monthsToShow - 1));
    }
  };

  DatePicker.prototype._monthPanel = function (monthDate, showPrev, showNext) {
    var self = this;
    var panel = document.createElement('div');
    panel.className = 'datepicker__month';

    // Header — title opens month view (only meaningful for single-panel)
    var header = this._header(fmtMonthYear(monthDate), this.monthsToShow === 1 ? 'months' : null);
    // For dual month, show only the relevant nav arrow per panel
    if (this.monthsToShow === 2) {
      var navBtns = header.querySelectorAll('.datepicker__nav-btn');
      navBtns[showPrev ? 1 : 0].style.visibility = 'hidden';
    }
    panel.appendChild(header);

    // Weekday row
    var wk = document.createElement('div');
    wk.className = 'datepicker__weekdays';
    WEEKDAYS.forEach(function (d) {
      var c = document.createElement('div');
      c.className = 'datepicker__weekday';
      c.textContent = d;
      wk.appendChild(c);
    });
    panel.appendChild(wk);

    // Grid
    var grid = document.createElement('div');
    grid.className = 'datepicker__grid';

    var year = monthDate.getFullYear(), month = monthDate.getMonth();
    var first = new Date(year, month, 1);
    var offset = (first.getDay() + 6) % 7; // Monday-first offset
    var startDate = new Date(year, month, 1 - offset);

    for (var i = 0; i < 42; i++) {
      var d = new Date(startDate.getFullYear(), startDate.getMonth(), startDate.getDate() + i);
      grid.appendChild(this._dayCell(d, month));
    }
    panel.appendChild(grid);
    return panel;
  };

  DatePicker.prototype._dayCell = function (d, currentMonth) {
    var self = this;
    var cell = document.createElement('button');
    cell.type = 'button';
    cell.className = 'datepicker__cell';
    cell.textContent = d.getDate();

    var disabled = this.isDisabled(d);
    var muted = d.getMonth() !== currentMonth;
    var isToday = sameDay(d, this.today);

    if (muted) cell.classList.add('datepicker__cell--muted');
    if (disabled) cell.classList.add('datepicker__cell--disabled');

    if (this.mode === 'single') {
      if (sameDay(d, this.selected)) cell.classList.add('datepicker__cell--selected');
      else if (isToday) cell.classList.add('datepicker__cell--today');
    } else {
      var s = this.rangeStart, e = this.rangeEnd;
      if (s && sameDay(d, s)) cell.classList.add('datepicker__cell--range-start');
      else if (e && sameDay(d, e)) cell.classList.add('datepicker__cell--range-end');
      else if (s && e && d > s && d < e) cell.classList.add('datepicker__cell--in-range');
      else if (isToday) cell.classList.add('datepicker__cell--today');
      if (isToday && s && e && d > s && d < e) cell.classList.add('datepicker__cell--today');
    }

    if (!disabled) {
      cell.addEventListener('click', function () { self._pickDay(d); });
    } else {
      cell.setAttribute('aria-disabled', 'true');
    }
    return cell;
  };

  DatePicker.prototype._pickDay = function (d) {
    if (this.mode === 'single') {
      this.selected = d;
      this.cursor = new Date(d.getFullYear(), d.getMonth(), 1);
      if (this.input) this.input.value = fmtDate(d);
      this.render();
      if (this._close) this._close();
    } else {
      if (!this.rangeStart || (this.rangeStart && this.rangeEnd)) {
        this.rangeStart = d; this.rangeEnd = null;
      } else if (d < this.rangeStart) {
        this.rangeEnd = this.rangeStart; this.rangeStart = d;
      } else {
        this.rangeEnd = d;
      }
      if (this.input && this.rangeStart && this.rangeEnd) {
        this.input.value = fmtDate(this.rangeStart) + ' — ' + fmtDate(this.rangeEnd);
      }
      this.render();
    }
    if (typeof this.onSelect === 'function') this.onSelect(this.value());
  };

  // ── Months view ───────────────────────────────────────
  DatePicker.prototype._renderMonths = function () {
    var self = this;
    var panel = document.createElement('div');
    panel.className = 'datepicker__month';
    panel.appendChild(this._header(String(this.cursor.getFullYear()), 'years'));

    var grid = document.createElement('div');
    grid.className = 'datepicker__grid datepicker__grid--months';
    MONTHS_SHORT.forEach(function (name, idx) {
      var cell = document.createElement('button');
      cell.type = 'button';
      cell.className = 'datepicker__cell';
      cell.textContent = name;
      var isSelected = self.selected && self.selected.getFullYear() === self.cursor.getFullYear() && self.selected.getMonth() === idx;
      var isCurrent = self.today.getFullYear() === self.cursor.getFullYear() && self.today.getMonth() === idx;
      if (isSelected) cell.classList.add('datepicker__cell--selected');
      else if (isCurrent) cell.classList.add('datepicker__cell--current');
      cell.addEventListener('click', function () {
        self.cursor = new Date(self.cursor.getFullYear(), idx, 1);
        self.view = 'days';
        self.render();
      });
      grid.appendChild(cell);
    });
    panel.appendChild(grid);
    this.months.appendChild(panel);
  };

  // ── Years view ────────────────────────────────────────
  DatePicker.prototype._renderYears = function () {
    var self = this;
    var y = this.cursor.getFullYear();
    var start = y - (((y % 12) + 12) % 12); // 12-year page aligned
    var panel = document.createElement('div');
    panel.className = 'datepicker__month';

    var header = this._header(start + ' — ' + (start + 11), null);
    panel.appendChild(header);

    var grid = document.createElement('div');
    grid.className = 'datepicker__grid datepicker__grid--years';
    for (var i = 0; i < 12; i++) {
      (function (yr) {
        var cell = document.createElement('button');
        cell.type = 'button';
        cell.className = 'datepicker__cell';
        cell.textContent = yr;
        if (self.selected && self.selected.getFullYear() === yr) cell.classList.add('datepicker__cell--selected');
        else if (self.today.getFullYear() === yr) cell.classList.add('datepicker__cell--current');
        cell.addEventListener('click', function () {
          self.cursor = new Date(yr, self.cursor.getMonth(), 1);
          self.view = 'months';
          self.render();
        });
        grid.appendChild(cell);
      })(start + i);
    }
    panel.appendChild(grid);
    this.months.appendChild(panel);
  };

  // ── Footer ─────────────────────────────────────────────
  DatePicker.prototype._renderFooter = function () {
    var self = this;
    var footer = document.createElement('div');
    footer.className = 'datepicker__footer';

    var label = document.createElement('span');
    label.className = 'datepicker__selected';

    var hasSelection = (this.mode === 'single' && this.selected) ||
      (this.mode === 'range' && this.rangeStart && this.rangeEnd);
    if (this.mode === 'single' && this.selected) {
      label.textContent = 'Selected: ' + fmtDate(this.selected);
    } else if (this.mode === 'range' && this.rangeStart && this.rangeEnd) {
      label.textContent = fmtDate(this.rangeStart) + ' — ' + fmtDate(this.rangeEnd);
    }

    var todayBtn = document.createElement('button');
    todayBtn.type = 'button';
    todayBtn.className = 'datepicker__today-btn';
    todayBtn.textContent = 'Today';
    todayBtn.addEventListener('click', function () {
      self.view = 'days';
      self.cursor = new Date(self.today.getFullYear(), self.today.getMonth(), 1);
      if (self.mode === 'single') {
        self.selected = self.today;
        if (self.input) self.input.value = fmtDate(self.today);
      }
      self.render();
    });

    // Match Figma: footer hidden entirely when nothing is selected
    if (!hasSelection) footer.hidden = true;

    footer.appendChild(label);
    footer.appendChild(todayBtn);
    this.cal.appendChild(footer);
  };

  DatePicker.prototype.value = function () {
    if (this.mode === 'single') return this.selected;
    return { start: this.rangeStart, end: this.rangeEnd };
  };

  function initDatePickers(scope) {
    (scope || document).querySelectorAll('[data-datepicker]').forEach(function (el) {
      if (!el.__datepicker) el.__datepicker = new DatePicker(el);
    });
  }

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { initDatePickers(); });
  } else {
    initDatePickers();
  }

  window.DatePicker = DatePicker;
  window.initDatePickers = initDatePickers;
})();
